import { Model } from "@vuex-orm/core";

export default class Season extends Model {
    static entity = "seasons";

    static fields() {
        return {
            id: this.attr(null),
            tid: this.attr(null),
            season: this.attr(null),
            seasonSplit: this.attr(null),
            gp: this.attr(null),
            gpHome: this.attr(null),
            att: this.attr(null),
            cash: this.attr(null),
            won: this.attr(null),
            lost: this.attr(null),
            wonSummer: this.attr(null),
            lostSummer: this.attr(null),
            wonSpring: this.attr(null),
            lostSpring: this.attr(null),
            wonHome: this.attr(null),
            lostHome: this.attr(null),
            wonAway: this.attr(null),
            lostAway: this.attr(null),
            wonDiv: this.attr(null),
            lostDiv: this.attr(null),
            wonConf: this.attr(null),
            lostConf: this.attr(null),
            lastTen: this.attr(null),
            streak: this.attr(null),
            cidStart: this.attr(null),
            cidMid: this.attr(null),
            cidNext: this.attr(null),
            countrySpecific: this.attr(null),
            playoffRoundsWon: this.attr(null),
            playoffRoundsWonMSI: this.attr(null),
            playoffRoundsWonNALCS: this.attr(null),
            playoffRoundsWonEULCS: this.attr(null),
            playoffRoundsWonLCK: this.attr(null),
            playoffRoundsWonLPL: this.attr(null),
            playoffRoundsWonLMS: this.attr(null),
            playoffRoundsWonNALCSPr: this.attr(null),
            playoffRoundsWonNACSPrA: this.attr(null),
            playoffRoundsWonNACSPrB: this.attr(null),
            playoffRoundsWonWorldsGr: this.attr(null),
            playoffRoundsWonWorldsReg: this.attr(null),
            playoffRoundsWonWorlds: this.attr(null),
            playoffRoundsWonMSIGr: this.attr(null),
            playoffRoundsWonMSIPlayIn: this.attr(null),
            playoffRoundsWonNALCSStay: this.attr(null),
            playoffRoundsWonNALCSStayEU: this.attr(null),
            playoffRoundsWonRegionals: this.attr(null),
            playoffRoundsWonMaybePlayoffs: this.attr(null),
            playoffRoundsWonNACSStay: this.attr(null),
            playoffRoundsWonNALadderStay: this.attr(null),
            ladderCSLCSStart: this.attr(null),
            ladderCSLCS: this.attr(null),
            pointsSpring: this.attr(null),
            pointsSummer: this.attr(null),
            hype: this.attr(null),
            pop: this.attr(null),
            revenues: this.attr(null),
            expenses: this.attr(null),
            payrollEndOfSeason: this.attr(null),
            rid: this.attr(null),
        };
    }
}
